#!/bin/bash

cd "$(dirname "$0")"
rm -rf docs/*
cd src
for f in $(find *)
do
    case $f in
	*.wm )
	    mkdir -p ../docs/$(dirname $f)
	    echo $f | cat - $f | snobol4 wm.sno > ../docs/${f%.wm}.html
	    ;;
	*.html | *.jpg )
	    cp $f ../docs/$f
	    ;;
	*.sno )
	    cp $f ../docs/${f%.sno}.txt
	    ;;
    esac
done

cd ..
cp -r ~/sutra-6/findwasm-src docs
