#!/bin/bash

cd "$(dirname "$0")"

rm -rf public/*
cd src

echo '```' > delim
cat delim ~/.scryerrc delim > aoc25pl/dotscryerrc.wm
rm delim

for f in $(find *)
do
    case $f in
	*.wm )
	    mkdir -p ../public/$(dirname $f)
	    echo $f | cat - $f | snobol4 wm.sno > ../public/${f%.wm}.html
	    ;;
	*.html | *.jpg )
	    cp $f ../public/$f
	    ;;
	*.sno )
	    cp $f ../public/${f%.sno}.txt
	    ;;
    esac
done

cd ..
